# Default config

#Wi-Fi interface's IP address on host
host_ip = ""

[AP_info]
# AP user credentials
ap_user = ""
ap_user_password = ""
ap_ip_control = ""
ap_wifi_iface = ""
ap_wifi_ip = ""
# One test time period (in seconds)

[defaults]
timeout = 10

#Bandwidth limit, default 0 -> no limited
bandwidth = 0

# Packet length for iperf3
# packet_length = 0 --> no limit
packet_length = 0

# Bidirectional: 1 - bidirectional / 0 - unidirectional
bidir = 0

# By default, AP transceives data to the host with this application
# reverse = 0 --> AP = TX & host = RX
# reverse = 1 --> AP = RX & host = TX
reverse = 0

# Packet fragmentation function performed by iperf3
# fragmentation: 0 - disabled / 1 - enabled
fragmentation = 1
